Parameters:
  Bucketname:
    Type: String


Resources:
  mys3bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref Bucketname
      VersioningConfiguration:
        Status: Enabled

